### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by pglez82** [Arquisoft/viade_en3a#1]
This a first issue just to break the ice. It would be great if you use the **issues system** to share all the information that you generate during this project. I would also be  good if you explore the **projects tool** in GitHub. It is quite useful to keep track of tasks and maintain everything organized. 

Here I put some useful links for you to start:

- [Solid Project](https://solidproject.org/)
- [React Native](https://facebook.github.io/react-native/)
- [React](https://es.reactjs.org/)
- [Another resource for learning React](https://www.kirupa.com/react/). This guy also has a book that is quite useful. It is called 'Learning React' but maybe is too expensive and you can find the same in the web.

And do not forget to write the **minutes** for all the meetings that you have. A good place to store them is the Wiki in this repository.

See you in the next session.

**Comment by jesQM** [comment]
An issue can be closed in a commit automatically with "Fixes #issueNumber" in the description of the commit.
As an example the following commit: 34bb32c1b373080a0181c3c39d2e1b1f246f396d
