### ISSUE TITLE
Bug on route listing feature

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#100]
Routes with only one point make route listing crash. But with two points at a minimum this works fine. I am thinking about not letting the user create routes with a single or no points since it doesn't make any sense whatsoever.

Any thoughts on the matter?

**Comment by oscar134** [comment]
Seems fair requiring a minimum of two points

**Comment by oscar134** [comment]
I fixed this. Now we check the input with the following constraints:
- Points should be at least two.
- Name can't be empty
- Description can't be empty
