### ISSUE TITLE
Discussion on whether we should include altitude in our points or not

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#107]
I have been having problems with including altitude inside the points of our model. This is because as the file is uploaded right after the route creation, the altitude API takes some ms to answer with the value for each pair of coordinates.

Due to this, and to the fact that if an altitude is retrieved, then the representation of the route changes, my current algorithm to not duplicate files inside the POD doesn't work properly. For this reason and given that we have limited time until the delivery, I think it is wise not to include it for now and maybe look this up later on for the final delivery.

What is your opinion guys?

**Comment by oscar134** [comment]
We can wait until all the altitudes are set and then upload the created route to the pod? Can't we?

**Comment by fincamd** [comment]
I will need to check it now that the json ld standard also includes altitude for the points. Or elevation rather... 

Will work on it.

**Comment by fincamd** [comment]
Elevation included following the JSON ld standard in viadespec
