### ISSUE TITLE
Bug on route info view

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#108]
Bug found while reloading the route info view. With a route created, you go to the route list, you see such route listed, you click on the info button, wait for the page to show up and then press F5 to reload the page. I think this would simply need to reload the page. 

It seems like that as we are treating routes and resources in general, when reloading the page, we are recreating all React components, navBar included (this one holds the routes inside the routeManager).

This needs to be looked up.

**Comment by jesQM** [comment]
I dont really understand the bug itself.
Is the bug just the long wait for all components to reload? or something else?

**Comment by fincamd** [comment]
Yeah, the problem is that when you look up the info of a route. If you for any reason reload the page itself, every single React component present is reloaded. This also creates a new RouteManager object which does not have enough time to retrieve routes from the pod and then it crashes because the route it is accessing to is undefined.

Maybe it is more clear if you try to reproduce it.

Log into the app, wait a little bit for the route request to complete, you can check this on F12, network section, then go to route list, pick a route if you have one (else create it, then list again), then go to its info. Once there try to reload the page

**Comment by fincamd** [comment]
So, I have created an issue that states the functionality that we'd need:

#113
