### ISSUE TITLE
Try to implement an async route card loading for route list view

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#113]
This have to be worked on so that the routes can be loaded asynchronously on the route list view.

Right now the app works but the user has to wait for a request to finish to be able to see their routes on the Route list view. Maybe this is hard to accomplish for this prototype v1.0. 

I reckon this has to do with the state of React components, and so updating it with newly fetched routes once they arrive to the client would be the solution. The state is not currently being used, but I have found a couple of websites talking about what I just need. I will conduct a small research after finishing the docs see if I can fix it.

**Comment by jesQM** [comment]
Dunno if this might help, but:
The current retrieval of routes from the pod is: all at the same time waiting for the last to be fetched and then return the array.
It can easily be changed so a function (a callback) is called when a route is fetched, so this would make it more "dynamic" as you can show stuff while the rest of the routes are loading.

However, it may alter the order of routes when displaying as you don't know the order in which they will come.

**Comment by fincamd** [comment]
I discovered how to do it yeah. This helped: [Link to react help page](https://itnext.io/react-setstate-usage-and-gotchas-ac10b4e03d60)

**Comment by fincamd** [comment]
Routes are now listed asynchronously when received from the POD.

It takes some time though :S. It is the best I could give.
