### ISSUE TITLE
Route sharing 

### ISSUE THREAD

**Issue by Drastur** [Arquisoft/viade_en3a#116]
Hi, 
I'm taking a look to [viadeSpec's issue concerning route sharing](https://github.com/Arquisoft/viadeSpec/issues/34) and I'm between two different aproaches:

### **User A** wants to share a route to **User B**

***Approach 1:*** 
User A shares the route by creating a file in the /inbox folder of User's B pod. This file contains the URI of the route shared.

Drawbacks
The routes of userA have to be inside a folder where everyone has access, such as /public. Security problems might arise as you can create infinite files inside your friends inbox.

***Approach 2:*** 
User A shares the route of User's B pod. Then, you do the following:

1. User A gives read permission to User B over the route shared.
2. User A creates a file in it's own POD inside /viade/routes/shared called userBwebID.json in where you store the URI of the route shared. In case this file already exist, a new entry is added for the shared route's URI.
3. User A gives User B read permissions over the json file.

Drawbacks
Im not sure by now on how to modify .acl files that give permission over folders and files, so further investigation is requiered.

**Comment by jesQM** [comment]
However, I believe following ViadeSpec will already decide for us this issue.
In order to read the routes, we all must write them in the same folder (either /viade or /public/viade), so depending on where the specification tells us to do se, we can already choose one approach or the other.
Not certain if I am correct, may easily be missing something.

**Comment by Drastur** [comment]
Just implemented the "notification" part, but not sure on how can we modify permissions of a folder. Any suggestion?

**Comment by jesQM** [comment]
#148 is taking care of the permissions issue, I will try to take care of it by:
* Trying to edit the .acl files as a normal file
* Trying external libraries that may help

Will post any further discovery in the other issue page.
