### ISSUE TITLE
Arc42 generation with npm

### ISSUE THREAD

**Issue by pglez82** [Arquisoft/viade_en3a#12]
Dear students,

Apparently asciidoc is not rewriting the html when generating the documentation. Here is a suggestion to ensure that everything is done properly (change this in package.json):

`shx rm -r build/docs && asciidoctor -D build/docs -a imagesdir=./images -r asciidoctor-diagram src/docs/index.adoc && shx cp -R src/docs/images build/docs`

Note that now we remove the build/docs directory before running asciidoctor. 

Pablo

**Comment by PabloFerMar** [comment]
Reopening because now, running the docs script works in local, but travis is failing because the directory build/docs does not exist in the repo since it´s declared in the .gitignore. Was this change just for working on local and should be reverted?

**Comment by pglez82** [comment]
Very good point. Just add the option f to the rm command so it ignores non existent directories:
`shx rm -rf build/docs && asciidoctor -D build/docs -a imagesdir=./images -r asciidoctor-diagram src/docs/index.adoc && shx cp -R src/docs/images build/docs'

**Comment by PabloFerMar** [comment]
Thanks, it´s solved now, travis build is passing
