### ISSUE TITLE
Create a view on the navbar to show a user manual about the application

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#140]
Maybe move user manual from readme to documentation as an extra point.

**Comment by fincamd** [comment]
Or maybe implement it to be accessible through ¿How do routes work? button present on the Navbar.

**Comment by jesQM** [comment]
Started some work on this issue: 3194d7447b13011c39189e08796d4f9b9c87caed.
Still much is left, I have just copied the readme onto the help view.

**Comment by jesQM** [comment]
#179 Just took care of this.
Some adjustments can still be done, but for now its ok, as all info in the readme has been moved we can change it with other content.
