### ISSUE TITLE
Add a place search feature to route creation map

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#143]
Route creation map not very usable. Users find themselves lost. Maybe we need to add a search feature to go to a specific point on the globe and start the route from there.

**Comment by oscar134** [comment]
I inserted a first prototype of how to search in the RouteCreation window. What do you think about it? I didn't like the already created components in npm for searching so I'm constructing my own. It has many possiblities. Like suggesting multiple places to go to the user. Do you think we should put much effort in having a very good searching system or is better concentrating in other issues and leave it very similar to what we have now?

**Comment by fincamd** [comment]
Well, what you did is impressive. I think it provides enough usability for what was suggested in the review. For now it will suffice, I think we should now focus in polishing other issues we currently have and later come back if some time is left.

**Comment by oscar134** [comment]
Ok. As soon as possible I will add some tests to this, and some error control to finish it.

**Comment by fincamd** [comment]
Got it. Great job mate. :D

**Comment by oscar134** [comment]
Basic implementation done. Can be enhaced but I will focus on things with more priority.

**Comment by fincamd** [comment]
I think that we could close this issue since it wont be worked on for a while until we wrap things up.

If you agree simply close this. We don't really need this issue anymore.

**Comment by oscar134** [comment]
Ok
