### ISSUE TITLE
Route points could follow standard's waypoint approach. Name and description

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#149]
Being able to edit points while creating a route. Have a list right beside the point addition map that allows to add information to the points. See if we are in Paris, we want to specify that on top of the Eiffel tower although the altitude is 300m we could specify that on that point: "Hey I am at the 10th floor of the Eiffel tower".

**Comment by oscar134** [comment]
The altitude will not change, but the name and description can be added to points

**Comment by oscar134** [comment]
Same issue as #175
