### ISSUE TITLE
Add loading icon

### ISSUE THREAD

**Issue by oscar134** [Arquisoft/viade_en3a#157]
In case some action will take time to be performed (ex: upload route to pod), show something to indicate that is loading (hourglass, wheel...). This way user can have more feedback

**Comment by fincamd** [comment]
Oh yes, you are completely right. I think React-bootstrap has some perfect fits for this purpose:
[Progress bars](https://react-bootstrap.github.io/components/progress/)
[Spinners](https://react-bootstrap.github.io/components/spinners/)

**Comment by oscar134** [comment]
Done.
