### ISSUE TITLE
Elevation Chart problem

### ISSUE THREAD

**Issue by oscar134** [Arquisoft/viade_en3a#161]
I don't know when it broke. But is broken. Elevation chart almost always shows -1 altitud for every point. Could you check if it happens the same to you or it's only my case?

**Comment by fincamd** [comment]
Sure thing! Going to check it right away. Maybe it is after media introduction modifications. If it shows -1 it is due to the point API request. Maybe something broke there.

**Comment by fincamd** [comment]
I have checked it and it works for me. I don't know what might have failed in your case. I'm sure we need to check that again.

**Comment by oscar134** [comment]
OK. I was reading the routes created before we implemented elevation. Now it works for me if it is a route that we created. But in case we create the route on another application that doesn't use elevation. Is displayed each point like -1. We could fix this asking for elevation if it's -1 when we download it.

**Comment by fincamd** [comment]
OK I got it now. That would solve it yes. :D

**Comment by fincamd** [comment]
Fixed on #177
