### ISSUE TITLE
Correct home and profile page to get the username correctly

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#165]
Modify the home and profile view of the username in order to get it correctly without all the id. 
Also get from the pod more info for the profile.

**Comment by oscar134** [comment]
I have extracted the get username functionality in the home view to another class because I needed to use it in another part. Its query needs to be changed in order to be compatible with inrupt. Maybe you can take what I have refactored in my branch.

**Comment by oscar134** [comment]
Jesus and I talked a bit about this in the opened pull request

**Comment by jesQM** [comment]
Perhaps that class (src/model/Util.js) can be used to centralize all stuff regarding user details: friends, username...
Just to have all ldflex query methods (or any other format) in one same class.

**Comment by nicomencia** [comment]
Yes I think you are right, that might be the best idea in order to centralice all the methods getting info from the POD, in order to be used through the app

**Comment by oscar134** [comment]
Ok. You can review my pull request and merge if you want or work over it.

**Comment by nicomencia** [comment]
Getting name correctly in home and profile page using ldflex from utils.js in feature-profile-info. 
I'll keep working in more attributes.

**Comment by nicomencia** [comment]
Only name is under <http://xmlns.com/foaf/0.1/> the rest of attributes are under <http://www.w3.org/2006/vcard/ns#> so I cannot access from ldflex queries.

**Comment by nicomencia** [comment]
Name in profile works both in solid.community and inrupt providers

**Comment by nicomencia** [comment]
Username, address, phone and email displayed correctly
