### ISSUE TITLE
Username disapearing from home when translation is executed

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#166]
Once the translation is executed the username now disapears from the home page.

**Comment by fincamd** [comment]
@PabloFerMar Any idea on what could be happening?

**Comment by nicomencia** [comment]
I think it's because now as the get user info from the pod is centralized it's called in a function when the page loads appending it to the "Hi " in the element, but once the translation is executed is substitutes everything with "Hola ".
@PabloFerMar do you know if it would be possible to call the func also with the translation or inside the translation, or any other solution.

**Comment by nicomencia** [comment]
Same error in profile page now, as info is loading onLoad function

**Comment by jesQM** [comment]
Fixed, the translation was overriding the append of the username.
