### ISSUE TITLE
Documentation 04, 05 & 06

### ISSUE THREAD

**Issue by PabloFerMar** [Arquisoft/viade_en3a#17]
We will start working on the sections 04, 05 and 06 of the documentation.

**Comment by fincamd** [comment]
Im going to try and write something for section 4 of the documentation; about "Solution Strategy"

**Comment by PabloFerMar** [comment]
I´m going to start with 5 and 6. 

Very possible that for now they´ll stay as TBD, because as I understand it, in the building block view we show a decomposition of the modules of the system. I could maybe create a basic whitebox, but at this point it would be similar as the context and technical context views in part 3 of the documentation, and for sure it would change.

The same for part 6, in the runtime view we show how the modules and components interact to different scenarios, and for now, there are no components.

So, basic diagram that I´m not sure if it would be ok in this part of the documentation, or TBD, that does not look nice?

**Comment by fincamd** [comment]
As my teammate says, at the moment it is pretty difficult to document things that are not even done nor designed. Things like building blocks's shape are yet to be defined with further steps on the project definition and design.

At the moment all we can do is label it as TBD and as we progress on the implementation, we can update these areas of the documentation that are left untouched.
