### ISSUE TITLE
Modify tab name from 'React App' to 'Viade EN3A'

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#174]

**Comment by fincamd** [comment]
This has already been done on #171 pr. :D If you take a look to the modifications over index.html it has a new title: "Viade", if you prefer to say "Viade EN3A" go on ahead. I thought Viade was descriptive enough and that we didn't need to specify the group. After all it is just the name of the page and browser tab.

Do as you wish mate :)

**Comment by nicomencia** [comment]
"Viade" is perfect for me. 
Sorry didn't notice that you were working on this, I just deployed the app this morning and "React App" appeared so though It was an important detail for the last version. 
I'm closing this.
