### ISSUE TITLE
Documentation 10 (Quality Requirements) and 11 (Risks and Technical Debts)

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#18]
We will divide the work as one writes it and the other revise it, when both assignees are ok with it, we will merge to the development branch. The division is the following:

* Quality Requirements: @nicomencia writes, @Drastur revises
* Risks and Technical Debts: @Drastur writes, @nicomencia revises

**Comment by Drastur** [comment]
Risks and Technical Debts section is finished is finished (currently in feature_arc42_10_11_doc  branch) and ready to be reviewed. @nicomencia 

Notify me when Quality Requirements is ready to check or if anything needs to be modified in Risks section! 😃

**Comment by nicomencia** [comment]
Just reviewed Risks and Technical Debts section @Drastur.
In my opinion the risks/debts identified are on point, also the solutions are valid and useful for each of them. I'll just point out that, as we start working with new technologies, we should add more rows to this table. Besides that I'ld like to mark that in the official arc42 documentation it's said that it has to be a list "ordered by priority", just in case you didn't bare in mind that.

I'm currently working on the Quality Requirements section, very likely it'll be finished for today.

**Comment by Drastur** [comment]
Thaks for the feedback! @nicomencia 

I noticed that it should be a "list ordered by priority", so they are ordered from the most important to the least. I think ill point it out before the table just to inform the readers in case they don't find out by themselves.

About using a list, I checked some past documentation from previous year, and some of them used I table as I did, just because incluiding the description and the solutions proposed in a list became to much of a mess. 

What's your opinion on this aproach? Should we ask the rest of the team?

**Comment by nicomencia** [comment]
Quality requirements section is ready for review (located in feature_arc42_10_11_doc branch). @Drastur

**Comment by nicomencia** [comment]
In my opinion it's a good idea to specify that the list is ordered by priority, just in case the reader is not familiarized with the arc42 system.

Based on my research I think the table format is the way to go in this case, it's far more easier to read than a simple list.

**Comment by Drastur** [comment]
Hey, just reviewed your work, seems pretty good to me! 
The only appreciation I might point out is that some of the descriptions of  quality attributes in the table seem to be unreachable, as for example, fully testing an app is beyond imposible, as Labra said in theory classes. I think we should approach it more cautiously, just trying to obtain a "high level" or "high degree", just more careful with what we write to be as precise as possible.

Anyways, I really liked the result. 👍

**Comment by nicomencia** [comment]
Nice to have your view. 
I think you are right, some of the descriptions are closer to an ideal, also impossible output, than a real goal. I'm changing them now.
