### ISSUE TITLE
Route List: Images displaying the map with the points of the routes get displaced on load

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#180]
The images displaying the map with the points of the routes gets displaced with further route card loading as the initial size measures the whole screen. When more routes are loaded, the image is then covered by new routes, hence covering the points of the first one.

Maybe looking through the component loading I can figure out a solution to this problem.

**Comment by fincamd** [comment]
If you modify the total size of the window say by for example opening up F12 and you close it, then the images get fixed. Maybe I have to do something like this programmatically...

What are your thoughts on the case?

**Comment by oscar134** [comment]
To solve this maybe we have to call again the map to re-fit in the new size. I think, this is not easy to solve.

**Comment by fincamd** [comment]
Fixed on #177
