### ISSUE TITLE
Include solid photo and better desing to the profile

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#184]
It would be nice to include, as well as all the new information showed, the photo of the user in the profile and a link to it's solid card, in order to edit something if he wants.
Also it would be nice to get a redesing on the profile page.

**Comment by Drastur** [comment]
I refactored the methods to print user info to prevent warnings using JQuery

**Comment by nicomencia** [comment]
The profile view now has a better look.
Also added load photo from Solid profile and link to solid profile card in a 'Solid color' button.
