### ISSUE TITLE
Do you want to include last routes in profile?

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#185]
Do you think it would be nice to include the last routes (last 2 for example, ordered by date) in the profile page or just remove that section?

**Comment by jesQM** [comment]
It would indeed look cool, however we must consider the amount of time we have left and whether it is easy or hard to implement.
In case we can access the routeManager it may be piece of cake, if not, it may be cumbersome.

**Comment by nicomencia** [comment]
As we are so close to the final delivery, we are not implementing this finally
