### ISSUE TITLE
Any methodology to be implemented??

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#21]
Hello there, I was trying to write some piece of the documentation. Point 4 about "solution strategy" and I stumbled across some examples that offered working methodologies as something to write about in this section.

So I would like to know about your opinion on whether we should implement some methodology like SCRUM for instance.

If it were for me, I would prefer not to do it. In my opinion GIT is already a source and version control, allows us to divide workflow using branches and GitHub offers plenty of tools to keep track of our progress. Projects and Issues for example.

What do you think? Thanks guys :D

**Comment by Drastur** [comment]
I completely agree with you about that point, GitHub seems to offer all the tools we need to distribute work and plan everything, so in the end no methodology is fully applied to our project right?

Making use of the projects tool is also really interesting, it seems to be close to a Kanban, which was very usefull in other subjects. I think we should take a look into it and organize one for upcoming tasks!

**Comment by oscar134** [comment]
For me is fine not using any pure metodology. We have here the tools we need for organize ourselves.

**Comment by fincamd** [comment]
As we seem not to be interested in any methodology I proceed to close this issue. Thanks for your opinions :D
