### ISSUE TITLE
Template project/application generation

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#32]
Guys, do you remember the generator-solid-react thing that we were talked about in SOLID conference last day?

I think I found their repository and I think we can install it into our project so it can create the basic skeleton for us. [https://github.com/inrupt/generator-solid-react]

What do you think?

**Comment by PabloFerMar** [comment]
Well, we talked about it in the lab today, but just so it´s in here too, we could test on another repo first to see what benefits could we get if we use it instead of how this repo is configured now, at least that´s what I understood about it.
