### ISSUE TITLE
Create SOLID PODs and accounts

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#4]
Further investigation is needed on how to create an account for the SOLID thing

**Comment by oscar134** [comment]
Basic application using Solid pods:
https://solid.inrupt.com/docs/app-on-your-lunch-break

**Comment by jesQM** [comment]
https://uo263624.solid.community/profile/card#me
Created a POD, just posting it here, in case someone knows what to do next.

**Comment by Drastur** [comment]
This is mine: https://drastur.solid.community/profile/card#me

**Comment by PabloFerMar** [comment]
Mine: https://pablofm.solid.community/profile/card#me

**Comment by fincamd** [comment]
Mine is also created: https://fincamd.solid.community/profile/card#me

**Comment by oscar134** [comment]
I also have one: https://oscar134.solid.community/profile/card#me

**Comment by nicomencia** [comment]
Mine: https://nicomencia.solid.community/profile/card#me

**Comment by fincamd** [comment]
Mistakes were made... Reopening this issue

**Comment by nicomencia** [comment]
https://nicoviadea1.solid.community/profile/card#me
https://nicoviadea2.solid.community/profile/card#me
