### ISSUE TITLE
Application nav bar

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#40]
I will try to create a nav bar component. Or investigate first if there is some out there online.

**Comment by jesQM** [comment]
Just created some tests regarding the nav functionality (using routes to change the view) with cd4ec7354131d1ecbe2abc250df90ecabdadf88a.
For now it is on another branch, and should not be merged into master as it may cause some problems:
The <Route> is sensible to the web reference, which works fine in localhost, but may cause trouble on github pages.

**Comment by Drastur** [comment]
Navbar is implemented now in development branch.
 #62
