### ISSUE TITLE
Options for the login navbar

### ISSUE THREAD

**Issue by Drastur** [Arquisoft/viade_en3a#44]
What options should be included in the nav bar for the initial page of the app?

Here you can se an example of the navbar in case you need some inspiration:

![image](https://user-images.githubusercontent.com/57039850/75983078-179fe580-5ee8-11ea-9da0-cc88e544e219.png)

(In relation to #36)

**Comment by fincamd** [comment]
It might be sorted out already but just in case it is not. The pair sign in, sign up at a minimum. Maybe we could have some option to route to the home/index(?) page? Maybe as well as a shortcut to one's profile and both on profile access and on the navbar I think that we should include a link to the route list view.

**Comment by fincamd** [comment]
From the route listing view we might also include the action to create a new route. It seems logical to me.

**Comment by Drastur** [comment]
Right now, the options in the nav bar are the following:
*For non-authenticated users
![image](https://user-images.githubusercontent.com/57039850/76402582-e873f300-6383-11ea-99a9-a5fdf6b7eb44.png)
*For authenticated users
![image](https://user-images.githubusercontent.com/57039850/76402696-0e999300-6384-11ea-9df5-86d611af533a.png)


In case any other entry needs to be added feel free to do it.
