### ISSUE TITLE
Friends CRUD

### ISSUE THREAD

**Issue by jesQM** [Arquisoft/viade_en3a#55]
Create a CRUD for friends of the logged in user.
May probably use rdf to do so, as I couldn't find anything regarding add/update/remove of data of pods.
For listing lbflex may do the trick.

**Comment by Drastur** [comment]
Im going to develop an option to add and delete users from the pod from the application.

**Comment by Drastur** [comment]
Listing for friends is done in branch feature-share-routes

**Comment by nicomencia** [comment]
For the moment we will not implement the CRUD in our app
