### ISSUE TITLE
Documentation (01 Introduction and goals)

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/viade_en3a#6]
Finish the introduction section composed by:

- General introduction
- Requirements overview
- Quality goals
- Stakeholders

**Comment by Drastur** [comment]
Here is what Nico and I did in the first session for the introduction part of the documentation. Only the stakeholder's part is missing, but you guys can give it a look in case anything should be modified. I'll start to translate it into ASCIIdoctor. 

Any feedback is welcomed! @nicomencia @fincamd @jesQM @oscar134 @PabloFerMar 
[Intro ASW documentacion.txt](https://github.com/Arquisoft/viade_en3a/files/4169729/Intro.ASW.documentacion.txt)

**Comment by Drastur** [comment]
I have pushed the adoc with the introduction and goals to the branch feature_arc42_01introduction. In the end I have modified some of the original text I shared to you guys in the previous message beacuse I think it didn't meet the specifications asked in the template. I've also finished stakeholders' section too, so just take a look to it if possible! :P

**Comment by nicomencia** [comment]
Just added a few modifications in the Stakeholders part, in my opinion is ready to merge.
