### ISSUE TITLE
Documentation 02_constraints

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#7]
Constraints documentation section being worked on

**Comment by fincamd** [comment]
In the lab session we took a look at previously created documentations. This would allow us to grasp how to write this specific section of the documentation.

**Comment by PabloFerMar** [comment]
We separated the work to be done between both of us, @fincamd writes about the technical constraints, and I write about the organizational constraints and conventions.

**Comment by fincamd** [comment]
@PabloFerMar We should write a minutes about last day session. Met in discord to write the constraints of the system.

**Comment by PabloFerMar** [comment]
Just merged my branch of organizational constraints to the main constraints one. Created also the new page on the wiki for the discord call.

**Comment by fincamd** [comment]
Okey, copy that. I think we might now merge the branch with the master one. What do you think? Let me know so we can close this issue.

I will merge it as soon as you answer to this comment :D. @PabloFerMar

**Comment by PabloFerMar** [comment]
Yeah, we can merge them now
