### ISSUE TITLE
Research on how to create friend groups needed

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#77]
Positive to follow this vocabulary: [SIOC-Spec](https://www.w3.org/Submission/sioc-spec/)

**Comment by nicomencia** [comment]
I'm starting dev this feature in feature-group-friends.
Friends view will by modified from showing cards of friends to showing groups of friends.

**Comment by nicomencia** [comment]
SIOC-Spec seems too complex just to create users and groupsusers, it involves also containers, forums, items, posts, roles, sites, etc that we are not going to implement.
Despite this we could use a very reduce part of the user and groupuser definiton, most of the properties are unused but member_of, avatar and email for user and has_member and usergroup_of for usergroup

**Comment by nicomencia** [comment]
Adding to this we could implement also the property creator_of for users and create Items inside Containers for the routes and adding their authorship, using SIOC-Spec also.
Could you review this? @fincamd @Drastur @jesQM @oscar134 @PabloFerMar

**Comment by fincamd** [comment]
I am afraid that people have started to define a proposal for a standard way to manage friend groups.

https://github.com/Arquisoft/viadeSpec/issues/38.

I am afraid that is not mature enough to get to development just yet. We'd need more oppinions from other teammates so we can agree on what to do.

**Comment by nicomencia** [comment]
Thanks for pointing me this out. I'll check it out and see if it can be pushed to get to dev,

**Comment by nicomencia** [comment]
New pages Groups and createGroups implemented.
Modified navbar link from friends to groups.
FriendCards modified for new use.
Groups page has a button to createGroups, friends are displayed here with a button for adding to the group and a create button.
Currently working on storing friends added to a list in order to create the group file and save it to the POD.

**Comment by nicomencia** [comment]
Created MyGroup and GroupManager in order to manage groups and it's correspondant files similar as we do with the routes.

**Comment by nicomencia** [comment]
I'll be implementing this format:

https://github.com/Arquisoft/viadeSpec/issues/38.

Except the name in users, bc as many people are poing out, it's useless.

**Comment by nicomencia** [comment]
I'll add an uuid as we do with the routes for not repeating files if a group has the same name.

**Comment by nicomencia** [comment]
Groups json files are now saved on the PODs user in viade/groups, containing members url, group name and a uuid.

**Comment by nicomencia** [comment]
Friends now can only be added once, if more a error notification appears and aren't added to the json file.

**Comment by nicomencia** [comment]
Groups now are loaded from pod each time groups view is accesed and they are displayed there with it's correspondent users.

**Comment by nicomencia** [comment]
Working in getting a better view for groups. Friends cards are loaded correctly.

**Comment by nicomencia** [comment]
Groups creation, store in POD, get from POD and display done
