### ISSUE TITLE
Improve internal Route management system

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#91]
So, @oscar134 proposed a model to internally manage route manipulation.

This is his proposal:

![WhatsApp Image 2020-03-23 at 17 20 43](https://user-images.githubusercontent.com/37817126/77454696-2dbf0880-6df9-11ea-9324-54ec074c9e8e.jpeg)
![WhatsApp Image 2020-03-23 at 17 18 54](https://user-images.githubusercontent.com/37817126/77454704-2ef03580-6df9-11ea-89b0-ea7c07d182b4.jpeg)

**Comment by fincamd** [comment]
My idea is to modify this design to try and make it a little simpler. I will work on it and upload my modified version to this issue to keep track of the progresses made.

**Comment by fincamd** [comment]
This is my proposal for the changes on the original one made by @oscar134.

![image](https://user-images.githubusercontent.com/37817126/77476900-c9617080-6e1b-11ea-9d67-4be1686cad9a.png)
![image](https://user-images.githubusercontent.com/37817126/77477708-09752300-6e1d-11ea-980f-0f04125bc04e.png)

I removed RouteCreator and performed some changes that can be seen in this pull request: .

**Comment by oscar134** [comment]
I like it. Extracting the route points benefits cohesion.

**Comment by fincamd** [comment]
Great! I am happy you like it. I am giving the PR the finishing touches. It should be out soon for you to check out.

I have also modified the way the routes are shown in CardDecks components from Bootstrap.
