### ISSUE TITLE
Improvement over Route info view's interface

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#92]
I have been thinking about a new layout for our route info view.

My proposal for a change would feature a carousel that shows the images provided for the route, and all the information that is provided in the serialised route files coming from the pod.

I will generate a mock-up for you to get a better view of what I am thinking about.

**Comment by fincamd** [comment]
Here is my proposal for you to check out.

It is thought for using a browser but css can be set up so that when using smaller screens, components arange themselves in an acceptable fashion to be readable.

![image](https://user-images.githubusercontent.com/37817126/77464905-2ce1a300-6e08-11ea-8454-d41594da208a.png)

**Comment by oscar134** [comment]
And what about the map. Will be shown in this view? Also I think the elements in the right column should be interchanged with those on the right. In order to focus first on the route name and data. The rest is fine for me.

**Comment by fincamd** [comment]
Hmm, yeah I think your arrangement proposal is much better...

Is this what you ment?

![image](https://user-images.githubusercontent.com/37817126/77522121-fcd7e580-6e83-11ea-865c-83c6b6795395.png)

Also, we might wanna include a link to a media view... But I think that is too much jumping around so there has to be another way to show media. This is motivated because I think the view is a little bit full with information and can be a little bit stressful to see so many things on the screen.

What do you think?
