### ISSUE TITLE
Implementing memoisation over route creation point addition (Images requests)

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#95]
@oscar134 Do you know if the map creation component can also be modified so it memoises the image of the points on the leaflet map? Is it something internal to the package? Because it seems to me that creating a request for the same image n times for the total number of points of a new route is too much.

I think these are the URIs which are being requested every single time back-to-back.,

https://unpkg.com/leaflet@1.6.0/dist/images/marker-icon.png
https://unpkg.com/leaflet@1.6.0/dist/images/marker-shadow.png

**Comment by oscar134** [comment]
I know you can edit the icon. But I have to investigate more.

**Comment by fincamd** [comment]
This is kind of useless to work on. I don't think that a couple of requests of an icon 24x24 is going to make a difference
