### ISSUE TITLE
Redesign route creation view

### ISSUE THREAD

**Issue by fincamd** [Arquisoft/viade_en3a#98]
Create a new layout for the route creation view.

**Comment by oscar134** [comment]
I've seen that in other places they remove a point by clicking again over it. It's smoother than our method of clicking the marker and also the delete buton. But I remember having some issues trying to achieve that in first instance. It's something to investigate about.

**Comment by oscar134** [comment]
Ok. That was easier to fix than expected. Removing marker problem solved.

**Comment by fincamd** [comment]
First prototype: 

![image](https://user-images.githubusercontent.com/37817126/79611980-11627300-80fc-11ea-9bd4-947f3ae9acb8.png).

**Comment by fincamd** [comment]
Proposed modifications:
- Increase margin above title.
- Move search bar above map.
- Replace Search word on button with a magnifying glass icon.
- Add an elevation chart to the blank space to the right to keep track of the route points and their respective altitude. Updated with each point addition.
- Also place media uploading tool to the blank space to the right of the map.
- Managing waypoints in this view is not considered.

**Comment by fincamd** [comment]
Done, now route creation view has a different layout.
